### ISSUE TITLE
mgie inference error

### ISSUE THREAD

**Issue by Zerycii** [ritwikraha/GenerativeFill-with-Keras-and-Diffusers#5]
Traceback (most recent call last):
  File "/content/ml-mgie/extract_ckpt.ipynb", line 5, in <module>
    "execution_count": null,
NameError: name 'null' is not defined

**Comment by Zerycii** [comment]
How can I solve the problem? I want to test the model on Colab

**Comment by Zerycii** [comment]
![image](https://github.com/ritwikraha/Open-Generative-Fill/assets/142808087/ad17eca0-6339-46ef-8d80-421323e804b8)
I change 'null' of code to 'None'. Then no error but it seems doesn't work.

**Comment by ritwikraha** [comment]
@Zerycii I think you are trying to run code from this repository: https://github.com/apple/ml-mgie

In that case I think its best if you raise this issue in that repository

Also you are trying to run an `.ipynb` file using the `!python` command
That only works for `.py` files, you can copy-paste the cells of a python notebook (`.ipynb`) inside a colab and get them to work. 

All the best :)
